name: Test
on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependacies
        run: |
          cd $GITHUB_WORKSPACE
            python -m pip install --upgrade pip
            pip install -r reqirement.txt
      - name: Run Tests
        run: python -m unittest test/*.py